todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
                # add task
        path('addTask/', views.addTask, name='addTask'),
                # mark as done
        path('mark_as_done/<int:pk>/', views.mark_as_done, name='mark_as_done'),
                # mark as undone
        path('mark_as_undone/<int:pk>/', views.mark_as_undone, name='mark_as_undone'),
                # edit task
        path('edit_task/<int:pk>/', views.edit_task, name='edit_task'),
        # delete task
        path('delete_task/<int:pk>/', views.delete_task, name='delete_task'),


]

todo_main/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', views.home, name='home'),  
    path('todo/', include('todo.urls')),

    
]

todo/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task = models.CharField(max_length=250)
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.task
    
        

todo/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from .models import Task

def addTask(request):
    task = request.POST['task']
    Task.objects.create(task=task)
    return redirect('home')

def mark_as_done(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_completed = True
    task.save()
    return redirect('home')

def mark_as_undone(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_completed = False
    task.save()
    return redirect('home')

def edit_task(request, pk):
    get_task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        new_task = request.POST['task']
        get_task.task  = new_task
        get_task.save()
        return redirect('home')
    else:
        context = {
            'get_task': get_task,
        }
    return render(request, 'edit_task.html', context)

def delete_task(request, pk):
    delete_this_task = get_object_or_404(Task, pk=pk)
    delete_this_task.delete()
    return redirect('home')



# Create your views here.

todo_main/views.py
from django.shortcuts import render

from todo.models import Task

def home (request):
    tasks = Task.objects.filter(is_completed=False).order_by('-updated_at')
    completed_tasks = Task.objects.filter(is_completed=True)
    print(completed_tasks)
    context = {
        'obligation': tasks,
        'completed_tasks' : completed_tasks,
    }
    return render(request,'home.html', context)

templates/edit_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit task Django Todo Application</title>
    <!-- Bootstrap -->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
 <!-- Font Awesome Icons -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 
</head>
<body>
   <div class="container">
 <h3 class="pt-5 pb-5 text-center"> Django Todo Application - Edit task</h3>
 <form action="{% url 'edit_task' get_task.pk %}" method="POST" class="form">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_task" class="form-label">Add Task</label>
        <input type="text" name="task" maxlength="100" class="form-control" placeholder="Enter Task" value="{{ get_task.task}}">
    </div>
    <div class="mb-3">
        <input type="submit" value="Update" class="btn btn-primary">
    </div>
</form>
   </div>

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO LIST - Home</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <style>
        .form-control{
        padding: 1.375rem .75rem !important;
    }
    </style>
</head>
<body>
    <div class="container">
        <h3 class="pt-5 text-center">Django ToDo App</h3>
        <div class="row">
            <h4>My Day</h4>
            <p class="text-muted">{% now "jS F Y" %}</p>
            <div class="col-md-7 col-lg-7" style="height: 450px; overflow: scroll;">
                <!-- List of all the tasks for the day -->
                {% for duty in obligation %} 
                <div class="card m-1">
                    <div class="card-body">
                        {{ duty.task }}  
                        <span style="position: relative; float: right;">
                            <a href="{% url 'mark_as_done' duty.pk %} " class="btn btn-success"><i class="fa fa-check"></i> Mark as Done</a>
                            <a href="{% url 'delete_task' duty.pk %} " class="btn btn-danger"><i class="fa fa-trash"></i></a>

                            <a href="{% url 'edit_task' duty.pk %}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                        </span>
                    </div>
                </div>
            {% endfor %}
            </div>
            <div class="col-md-5 col-lg-5">
                <h5>Completed Tasks</h5>
                {% for task in completed_tasks %}
                <div class="card m-1">
                    <div class="card-body">
                        <span style="position: relative; float: right;">
                            <a href="{% url 'mark_as_undone' pk=task.id %}"class="btn btn-success"><i class="fa fa-check"></i> Mark as Undone</a>
                            <a class="btn btn-danger"><i class="fa fa-trash"></i></a>
                            <a class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                        </span>
                        
                        {{ task.task }}
                    </div>
                    
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="row pt-5">
            <div class="col-md-7 col-lg-7">
                <form action="{% url 'addTask'%}" method="POST" class="form">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_task" class="form-label">Add Task</label>
                        <input type="text" name="task" maxlength="100" class="form-control" placeholder="Enter Task">
                    </div>
                    <div class="mb-3">
                        <input type="submit" value="Add Task" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>